parameters:
  androidPool: { }
  iosPool: { }
  androidApiLevels: [ 30 ]
  iosVersions: [ '16.4' ]
  provisionatorChannel: 'latest'
  agentPoolAccessToken: ''
  projects:
    - name: name
      desc: Human Description
      android: /optional/path/to/android.csproj
      ios: /optional/path/to/ios.csproj

stages:

  - stage: android_device_tests
    displayName: Android Device Tests
    dependsOn: []
    jobs:
    - job: android_device_tests
      workspace:
        clean: all
      displayName: "Android emulator tests"
      pool: ${{ parameters.androidPool }}
      strategy:
        matrix:
          # create all the variables used for the matrix
          ${{ each project in parameters.projects }}:
            ${{ if ne(project.android, '') }}:
              ${{ each api in parameters.androidApiLevels }}:
                ${{ if not(containsValue(project.androidApiLevelsExclude, api)) }}:
                  ${{ replace(coalesce(project.desc, project.name), ' ', '_') }}_API_${{ api }}:
                    REQUIRED_XCODE: $(DEVICETESTS_REQUIRED_XCODE)
                    PROJECT_PATH: ${{ project.android }}
                    ${{ if eq(api, 27) }}:
                      DEVICE: android-emulator-32_${{ api }}
                    ${{ if not(eq(api, 27)) }}:
                      DEVICE: android-emulator-64_${{ api }}
      steps:
        - template: device-tests-steps.yml
          parameters:
            platform: android
            path: $(PROJECT_PATH) 
            device: $(DEVICE)
            windowsPackageId: android # Only needed for Windows, will be ignored
            provisionatorChannel: ${{ parameters.provisionatorChannel }}
            agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}
            artifactName: ${{ parameters.artifactName }}
            artifactItemPattern: ${{ parameters.artifactItemPattern }}
            checkoutDirectory: ${{ parameters.checkoutDirectory }}
            useArtifacts: ${{ parameters.useArtifacts }}

  - stage: ios_device_tests
    displayName: iOS Device Tests
    dependsOn: []
    jobs:
    - job: ios_device_tests
      workspace:
        clean: all
      displayName: "iOS simulator tests"
      pool: ${{ parameters.iosPool }}
      strategy:
        matrix:
          # create all the variables used for the matrix
          ${{ each project in parameters.projects }}:
            ${{ if ne(project.ios, '') }}:
              ${{ each version in parameters.iosVersions }}:
                ${{ if not(containsValue(project.iosVersionsExclude, version)) }}:
                  ${{ replace(coalesce(project.desc, project.name), ' ', '_') }}_V_${{ version }}:
                    REQUIRED_XCODE: $(DEVICETESTS_REQUIRED_XCODE)
                    PROJECT_PATH: ${{ project.ios }}
                    ${{ if eq(version, 'latest') }}:
                      DEVICE: ios-simulator-64
                    ${{ else }}:
                      DEVICE: ios-simulator-64_${{ version }}
      steps:
        - template: device-tests-steps.yml
          parameters:
            platform: ios
            path: $(PROJECT_PATH)
            device: $(DEVICE)
            windowsPackageId: ios # Only needed for Windows, will be ignored
            provisionatorChannel: ${{ parameters.provisionatorChannel }}
            agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}
            artifactName: ${{ parameters.artifactName }}
            artifactItemPattern: ${{ parameters.artifactItemPattern }}
            checkoutDirectory: ${{ parameters.checkoutDirectory }}
            useArtifacts: ${{ parameters.useArtifacts }}
